name: How to portal
permalink: none

baseurl: "/howto" # the subpath of your site, e.g. /blog/
url: "http://staging.globalforestwatch.org/" # the base hostname & protocol for your site


gems:
  - jekyll-archives

exclude: ["node_modules", "gulpfile.js", "package.json"]

jekyll-archives:
  enabled: [categories,tags]
  layouts:
    tag: tag
    category: category
  permalinks:
    category: '/categories/:name/'
    tag: '/tags/:name/'


# TAGS
tags_info:
  gfw:
    order: 1
    title: Gfw
    description: "Empowering people everywhere to better manage and conserve forest landscapes through an interactive online forest monitoring system."
    slug: gfw
    type: app    
  fires:
    order: 2
    title: Fires
    description: "Global Forest Watch Fires (GFW Fires) is an online platform for monitoring and responding to forest and land fires in the ASEAN region using near real-time information."
    slug: fires
    type: app    
  commodities:
    order: 3
    title: Commodities
    description: "Global Forest Watch Commodities is an online platform that empowers companies to analyze the impact of key commodities on forests, using the latest and most powerful data available."
    slug: commodities
    type: app    
  climate:
    order: 4
    title: Climate
    description: "GFW Climate catalyzes action on climate change by providing timely, credible answers to questions about carbon emissions from tropical deforestation."
    slug: climate
    type: app    
  odp:
    order: 5
    title: Open data portal
    description: "Browse, learn more about, and download the data displayed on Global Forest Watch."
    slug: odp
    type: tool    
  map_builder:
    order: 6
    title: Map Builder
    description: "Map Builder"
    slug: map-builder
    type: tool    
  small_grants_fund:
    order: 7
    title: Small Grants Fund
    description: "Small Grants Fund"
    slug: small-grants-fund
    type: tool    




# CATEGORIES
categories_info:
  visualize_data:
    order: 1
    title: Visualize Data
    description: "Some data are produced directly by WRI and our partners, such as FORMA alerts, Intact Forest Landscapes, and some forest use data."
    slug: visualize data
    type: subject
  view_statistics:
    order: 2
    title: View Statistics
    description: "These courses are designed to provide an in-depth understanding of the ways can support a variety of professional."
    slug: view statistics
    type: subject
  analyze_data:
    order: 3
    title: Analyze Data
    description: "Description analyze_data"
    slug: analyze data
    type: subject
  subscribe_to_alerts:
    order: 4
    title: Subscribe to Alerts
    description: "Description subscribe_to_alerts"
    slug: subscribe to alerts
    type: subject
  submit_a_story:
    order: 5
    title: Submit a story
    description: "Description submit_a_story"
    slug: submit a story
    type: subject
  download_data:
    order: 6
    title: Download data
    description: "Description download_data"
    slug: download data
    type: subject
  create_custom_maps:
    order: 7
    title: Create Custom Maps
    description: "Description create_custom_maps"
    slug: create custom maps
    type: subject
  gis:
    order: 8
    title: GIS
    description: "Description gis"
    slug: gis
    type: subject
  

 
  tutorial_videos:
    order: 9
    title: Tutorial videos
    description: "Description tutorial_videos"
    slug: tutorial videos
    type: material    
  webinars:
    order: 10
    title: Webinars
    description: "Description webinars"
    slug: webinars
    type: material    
  faqs:
    order: 11
    title: FAQ’s
    description: "Description faqs"
    slug: faqs
    type: material    
  training_modules:
    order: 12
    title: Training modules
    description: "Description training_modules"
    slug: training modules
    type: material    
  blogs:
    order: 13
    title: Blogs
    description: "Description blogs"
    slug: blogs
    type: material    




